package br.com.zazao.exerciciosjava.models;

public class GeradorPrimo extends NumerosPrimos{
    private void gerarProximoPrimo(){

    }

//
//    FALHEI EM RESOLVER ESSA TAREFAFALHEI EM RESOLVER ESSA TAREFAFALHEI EM RESOLVER ESSA TAREFAFALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFAFALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    V
//            VerificadorPrimoFALHEI EM RESOLVER ESSA TAREFA
//    V
//    FALHEI EM RESOLVER ESSA TAREFA
//



}
