package br.com.zazao.exerciciosjava.models;

public class VerificadorPrimo extends NumerosPrimos{
    private void verificarSeEhPrimo(){

    }
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFAFALHEI EM RESOLVER ESSA TAREFAFALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFAFALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//    FALHEI EM RESOLVER ESSA TAREFA
//



}
